version: '3.8'

services:
  php:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Palve@56
      MYSQL_DATABASE: attendence
    ports:
      - "3307:3306"